http://localhost:4000/

###

http://localhost:3000/status

###

http://localhost:4000/blocks

###

POST http://localhost:3000/blocks

{
    "message": "mine me!"
}

###

http://localhost:4000/blocks/00df69d9f7a87a87b137c9e6ffda0ddfbe2a7409523e6411a0d7a20756281303

###

POST http://localhost:4000/transactions

{
    "to":"nico",
    "amount":40
}

###

http://localhost:4000/balance/3466f83715fbc26a74152f4477b43b0084366c944f4df6a3a271ff978d05495990f57139d08dce2b3591d34cc72e9d71939c6e0422ca29845b4d29c95542ba54?total=true
// verify by private key

###

http://localhost:4000/balance/nico?total=true
// verify by public key

###

http://localhost:4000/mempool

###

http://localhost:4000/wallet

###

POST http://localhost:4000/peers

{
    "address": "127.0.0.1",
    "port": "3000"
}

###

POST http://localhost:3000/peers

{
    "address": "127.0.0.1",
    "port": "2000"
}

###

http://localhost:4000/peers